version: '3.7'

networks:
  agenda-petshop-network:
    driver: bridge

services:
  agenda-petshop-db:
    container_name: agenda-petshop-mysql
    image: mysql:5.7.28
    env_file: env/local-db-mysql.env
    ports:
      - 3307:3306
    networks:
      - agenda-petshop-network

  # agenda-petshop-api:
  #   container_name: agenda-petshop-graphql
  #   image: node:12.12.0
  #   volumes:
  #     - ./agenda-petshop/:/usr/api
  #   working_dir: /usr/api
  #   command: sh -c 'npm install && ./wait-for-it.sh agenda-petshop-db:3306 -- npm start'
  #   env_file: env/local-api-graphql.env
  #   ports:
  #     - 4000:4000
  #   networks:
  #     - agenda-petshop-network
  #   links:
  #     - agenda-petshop-db
  #   depends_on:
  #     - agenda-petshop-db

  agenda-petshop-api:
    container_name: agenda-petshop-graphql
    build:
      context: ./
      dockerfile: Dockerfile
    env_file: env/local-api-graphql.env
    ports:
      - 4000:4000
    networks:
      - agenda-petshop-network
    links:
      - agenda-petshop-db
    depends_on:
      - agenda-petshop-db
