version: '3.7'

networks:
  agenda-petshop-network:
    driver: bridge

services:
  agenda-petshop-db:
    image: mysql:5.7.28
    env_file: env/.env.local-db-mysql
    ports:
      - 3306:3306
    networks:
      - agenda-petshop-network

  agenda-petshop-api-graphql:
    build:
      context: ./
      dockerfile: agenda-petshop-api-graphql/Dockerfile
    env_file: env/.env.local-api-graphql
    ports:
      - 4000:4000
    networks:
      - agenda-petshop-network
    depends_on:
      - agenda-petshop-db

  agenda-petshop-api-rest:
    build:
      context: ./
      dockerfile: agenda-petshop-api-rest/Dockerfile
    env_file: env/.env.local-api-rest
    ports:
      - 4001:4001
    networks:
      - agenda-petshop-network
    depends_on:
      - agenda-petshop-db

  agenda-petshop-front-react:
    build:
      context: ./
      dockerfile: agenda-petshop-front-react/Dockerfile
    env_file: env/.env.local-front-react
    ports:
      - 3000:3000
    networks:
      - agenda-petshop-network
    depends_on:
      - agenda-petshop-api-graphql
      - agenda-petshop-api-rest
